### ISSUE TITLE
Problem with mapping of Creation Date

### ISSUE THREAD

**Issue by edgartdata** [american-art/aac_mappings#1] opened 2016-09-07 15:07 UTC
I expected to see:

_[between 1751 and 1752]_

but instead I saw:

_I SAW NOTHING!]_

The current query was:

``` ttl
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX crm: <http://erlangen-crm.org/current/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

SELECT ?display_date ?earliest_date ?latest_date ?production_event
WHERE {
<http://collection.britishart.yale.edu/id/object/499> a crm:E22_Man-Made_Object.
{
  <http://collection.britishart.yale.edu/id/object/499> crm:P108i_was_produced_by ?production_event .
} UNION {
  ?production_event crm:P108_has_produced <http://collection.britishart.yale.edu/id/object/499> .
} UNION {
  <http://collection.britishart.yale.edu/id/object/499> crm:P108i_was_produced_by ?intermediate_event .
  ?intermediate_event crm:P9_consists_of ?production_event .
}
?production_event a crm:E12_Production ;
  crm:P4_has_time-span ?production_timespan. 
?production_timespan a crm:E52_Time-Span.
OPTIONAL {
  {
   ?production_timespan crm:P82a_begin_of_the_begin ?earliest_date.
   ?production_timespan crm:P82b_end_of_the_end ?latest_date.
  } UNION {
    ?production_timespan crm:P82_at_some_time_within ?earliest_date.
    ?production_timespan crm:P82_at_some_time_within ?latest_date.
  }
}
OPTIONAL {
  {
    ?production_timespan crm:P3_has_note ?display_date. 
  } UNION {
    ?production_timespan skos:prefLabel ?display_date. 
  } UNION {
    ?production_timespan rdfs:label ?display_date. 
  }
}

}


```

**Comment by workergnome** [comment] 2016-09-07 15:29
I believe this is failing because there is no production event associated with that object.

<http://collection.britishart.yale.edu/sparql/?query=SELECT+DISTINCT+*+WHERE+%7B%0D%0A%7B%09%3Chttp%3A%2F%2Fcollection.britishart.yale.edu%2Fid%2Fobject%2F499%3E+%3Fp+%3Fo+.%0D%0A%7DUNION+%7B%0D%0A%3Fs+%3Fo+%3Chttp%3A%2F%2Fcollection.britishart.yale.edu%2Fid%2Fobject%2F499%3E.%0D%0A%7D%0D%0A%7D>

Does not show a `crm:P108_has_produced` or a ` crm:P108i_was_produced_by` predicate associated with that object.

Is there another way to discover the production event?

**Comment by edgartdata** [comment] 2016-09-07 18:49
Object http://collection.britishart.yale.edu/id/object/46794 returns a production event for me in Pubby: http://collection.britishart.yale.edu/id/page/object/46794 but it is on subsequent pages: http://collection.britishart.yale.edu/id/page/object/46794/production/1

But unfortunately that’s where it stops. I am sorry to say that it is not returning the name of the artist. Argh.

**Comment by workergnome** [comment] 2016-09-07 20:25
Interesting.  <http://collection.britishart.yale.edu/id/page/object/46794/production/1> doesn't return anything at all for me.  
 
![screen shot 2016-09-07 at 4 25 19 pm](https://cloud.githubusercontent.com/assets/34536/18327264/b662d01a-7517-11e6-8812-49530d4c076e.png)

Does it return different events if you're internal vs. external?

**Comment by workergnome** [comment] 2016-12-20 02:25
@edgartdata—closing this, since I don't think the issue is on my end.  Feel free to re-open if you need to.

**Closed by workergnome** 2016-12-20 02:25 UTC
